# -*- coding: utf-8 -*-
"""Assignmnent_Lansat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yn2CWrNGdjNg0r_1lpablyyYURJGFeCP
"""

import geemap,geemap as import_map
import ee

ee.Authenticate()
ee.Initialize(project='bha5vya')
map=import_map.Map()

studyarea=ee.FeatureCollection('projects/bha5vya/assets/Trivandrum')

landsat7 = ee.ImageCollection("LANDSAT/LE07/C02/T1").filterDate('2000-05-01', '2000-12-31')
landsat7_fcc_2000=landsat7.select('B4','B3','B2').mean().clip(studyarea)
landsat7_tcc_2000=landsat7.select('B3','B2','B1').mean().clip(studyarea)
map.addLayer(landsat7_fcc_2000,{},'FCC_2000')
map.addLayer(landsat7_tcc_2000,{},'TCC_2000')

landsat9 = ee.ImageCollection("LANDSAT/LC09/C02/T1").filterDate('2024-05-01', '2024-12-31')
landsat9_fcc_2024=landsat9.select('B5','B4','B3').mean().clip(studyarea)
landsat9_tcc_2024=landsat9.select('B4','B3','B2').mean().clip(studyarea)
map.addLayer(landsat9_fcc_2024,{},'FCC_2024')
map.addLayer(landsat9_tcc_2024,{},'TCC_2024') #adding TCC and FCC datasets of Landsat 9 for the year of 2024

map



