# -*- coding: utf-8 -*-
"""Assignmnent_Sentinel.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1USoMyWiRAfZZ1h4Rswm2qXfUw9xD0cnW
"""

import geemap,geemap as import_map
import ee

ee.Authenticate()
ee.Initialize(project='bha5vya')
map=import_map.Map()

studyarea=ee.FeatureCollection('projects/bha5vya/assets/Trivandrum')

sentinel_2016=ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2016-05-01', '2016-12-31')

sentinel_2016_tcc=sentinel_2016.select('B4','B3','B2').mean().clip(studyarea)
sentinel_2016_fcc=sentinel_2016.select('B8','B4','B3').mean().clip(studyarea)

map.addLayer(sentinel_2016_tcc,{},'TCC_2016')
map.addLayer(sentinel_2016_fcc,{},'FCC_2016')

sentinel_2024=ee.ImageCollection("COPERNICUS/S2_HARMONIZED").filterDate('2024-05-01', '2024-12-31')
sentinel_2024_tcc=sentinel_2024.select('B4','B3','B2').mean().clip(studyarea)
sentinel_2024_fcc=sentinel_2024.select('B8','B4','B3').mean().clip(studyarea)

map.addLayer(sentinel_2024_tcc,{},'TCC_2024')
map.addLayer(sentinel_2024_fcc,{},'FCC_2024')

map.center_object(studyarea,9)
map